version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...==========================================
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 681810644781.dkr.ecr.ap-northeast-2.amazonaws.com
      - aws eks --region ap-northeast-2 update-kubeconfig --name toppos
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Started to replace setting-files..
      - cp /src/main/resources/static/assets/js/AUIGrid/AUIGridLicense-release.js /src/main/resources/static/assets/js/AUIGrid/AUIGridLicense.js
      - cp /src/main/resources/application-release.properties /src/main/resources/application.properties
      - echo Started build phase..
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t toppos .
      - docker tag toppos:latest 681810644781.dkr.ecr.ap-northeast-2.amazonaws.com/toppos:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Image_Version - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 681810644781.dkr.ecr.ap-northeast-2.amazonaws.com/toppos:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo List directory
      - ls -la
      - echo Push the latest image to cluster
      - REPOSITORY_URI=681810644781.dkr.ecr.ap-northeast-2.amazonaws.com/toppos
      - sed -i 's@CONTAINER_IMAGE_TAG@'"$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"'@' k8s-deploy.yaml
      - S3_ACCESS_ID=${TOPPOS_S3_ACCESS_ID}
      - sed -i 's@TOPPOS_S3_ACCESS_ID_TAG@'"$S3_ACCESS_ID"'@' k8s-deploy.yaml
      - S3_ACCESS_KEY=${TOPPOS_S3_ACCESS_KEY}
      - sed -i 's@TOPPOS_S3_ACCESS_KEY_TAG@'"$S3_ACCESS_KEY"'@' k8s-deploy.yaml
      - AWS_REGION=${TOPPOS_AWS_REGION}
      - sed -i 's@TOPPOS_AWS_REGION_TAG@'"$AWS_REGION"'@' k8s-deploy.yaml
      - AWS_S3_BUCKET=${TOPPOS_AWS_S3_BUCKET}
      - sed -i 's@TOPPOS_AWS_S3_BUCKET_TAG@'"$AWS_S3_BUCKET"'@' k8s-deploy.yaml
      - AWS_S3_BUCKET_URL=${TOPPOS_AWS_S3_BUCKET_URL}
      - sed -i 's@TOPPOS_AWS_S3_BUCKET_URL_TAG@'"$AWS_S3_BUCKET_URL"'@' k8s-deploy.yaml
      - FILEUPLOAD_URL=${TOPPOS_FILEUPLOAD_URL}
      - sed -i 's@TOPPOS_FILEUPLOAD_URL_TAG@'"$FILEUPLOAD_URL"'@' k8s-deploy.yaml
      - DATASOURCE_HOST=${TOPPOS_DATASOURCE_HOST}
      - sed -i 's@TOPPOS_DATASOURCE_HOST_TAG@'"$DATASOURCE_HOST"'@' k8s-deploy.yaml
      - API_PROTOCOL=${TOPPOS_API_PROTOCOL}
      - sed -i 's@TOPPOS_API_PROTOCOL_TAG@'"$API_PROTOCOL"'@' k8s-deploy.yaml
      - DATASOURCE_PORT=${TOPPOS_DATASOURCE_PORT}
      - sed -i 's@TOPPOS_DATASOURCE_PORT_TAG@'"$DATASOURCE_PORT"'@' k8s-deploy.yaml
      - DATASOURCE_DBNAME=${TOPPOS_DATASOURCE_DBNAME}
      - sed -i 's@TOPPOS_DATASOURCE_DBNAME_TAG@'"$DATASOURCE_DBNAME"'@' k8s-deploy.yaml
      - DATASOURCE_USERNAME=${TOPPOS_DATASOURCE_USERNAME}
      - sed -i 's@TOPPOS_DATASOURCE_USERNAME_TAG@'"$DATASOURCE_USERNAME"'@' k8s-deploy.yaml
      - DATASOURCE_PASSWORD=${TOPPOS_DATASOURCE_PASSWORD}
      - sed -i 's@TOPPOS_DATASOURCE_PASSWORD_TAG@'"$DATASOURCE_PASSWORD"'@' k8s-deploy.yaml
      - kubectl apply -f k8s-deploy.yaml