apiVersion: apps/v1
kind: Deployment
metadata:
  name: toppos-deployment
  labels:
    app: toppos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toppos
  template:
    metadata:
      labels:
        app: toppos
    spec:
      containers:
        - name: toppos
          image: CONTAINER_IMAGE_TAG
          ports:
            - containerPort: 8020
              name: toppos-port
              protocol: TCP
          resources:
            requests:
              memory: "4"
              cpu: "2"
          env:
            - name: TOPPOS_S3_ACCESS_ID
              value: TOPPOS_S3_ACCESS_ID_TAG
            - name: TOPPOS_S3_ACCESS_KEY
              value: TOPPOS_S3_ACCESS_KEY_TAG
            - name: TOPPOS_AWS_REGION
              value: TOPPOS_AWS_REGION_TAG
            - name: TOPPOS_AWS_S3_BUCKET
              value: TOPPOS_AWS_S3_BUCKET_TAG
            - name: TOPPOS_AWS_S3_BUCKET_URL
              value: TOPPOS_AWS_S3_BUCKET_URL_TAG
            - name: TOPPOS_FILEUPLOAD_URL
              value: TOPPOS_FILEUPLOAD_URL_TAG
            - name: TOPPOS_DATASOURCE_HOST
              value: TOPPOS_DATASOURCE_HOST_TAG
            - name: TOPPOS_API_PROTOCOL
              value: TOPPOS_API_PROTOCOL_TAG
            - name: TOPPOS_DATASOURCE_PORT
              value: "TOPPOS_DATASOURCE_PORT_TAG"
            - name: TOPPOS_DATASOURCE_DBNAME
              value: TOPPOS_DATASOURCE_DBNAME_TAG
            - name: TOPPOS_DATASOURCE_USERNAME
              value: TOPPOS_DATASOURCE_USERNAME_TAG
            - name: TOPPOS_DATASOURCE_PASSWORD
              value: TOPPOS_DATASOURCE_PASSWORD_TAG